title: "  "
buildFuture: true
defaultContentLanguage: en
languageCode: ru
baseURL: https://ffbsoffa.org
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Вебсайт
      category: Основные модули
      description: Статус работы вебсайта
    - name: Модуль №1 (Звукорежиссура)
      category: Основные модули
    - name: Модуль №2 (учебный)
      category: Основные модули
  dateFormat: January 2, 2006 // 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 5
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - untitled: true
      name: Основные модули
  description: Статус занятости и статус работоспособности сайта
  enableCustomHTML: true
  useLargeHeaderDesign: false
